version: '3'
services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - local

#Docker Networks
networks:
  local:
    driver: bridge